name: flutter_template_3
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  get_storage: ^2.0.3
  cached_network_image: ^3.2.3
  image_cropper: ^3.0.1
  image_picker: ^0.8.6+1
  fluttertoast: ^8.1.2
  flutter_svg: ^1.1.6
  shimmer: ^2.0.0
  device_info_plus: ^8.0.0
  flutter_local_notifications: ^13.0.0
  timeago: ^3.3.0
  intl: ^0.17.0
  url_launcher: ^6.1.8
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_crashlytics: ^3.0.11
  dio: ^4.0.6
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1
  dartz: ^0.10.1
#  connectivity_plus: ^2.3.6+1
  permission_handler: ^10.2.0
  package_info: ^2.0.2
  google_sign_in: ^5.4.3
  sign_in_with_apple: ^4.3.0
  flutter_facebook_auth: ^5.0.7
  geolocator: ^9.0.2
  sms_autofill: ^2.2.0
  pin_code_fields: ^7.4.0
  in_app_update: ^4.1.0
  collection: ^1.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  widgetbook: ^2.4.1
  build_runner:
  widgetbook_generator:
  intl_utils:
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/mocks/
    - assets/anim/
flutter_intl:
  enabled: true