name: flutter_template_3
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.1.1
  cached_network_image: ^3.2.3
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  device_info_plus: ^9.0.3
  timeago: ^3.5.0
  intl: ^0.18.1
  url_launcher: ^6.1.14
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  dio: ^5.3.2
  logger: ^2.0.2
  pretty_dio_logger: ^1.3.1
  dartz: ^0.10.1
#  connectivity_plus: ^2.3.6+1
  permission_handler: ^11.0.0
  package_info: ^2.0.2
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  flutter_facebook_auth: ^6.0.2
  geolocator: ^10.0.1
  sms_autofill: ^2.3.0
  pin_code_fields: ^8.0.1
  in_app_update: ^4.2.1
  collection: 1.17.2
  awesome_notifications: ^0.7.4+1
  awesome_notifications_fcm: ^0.7.4+1
  android_path_provider: ^0.3.0
  flutter_downloader: ^1.11.2
  rive: ^0.11.16
  carousel_slider: ^4.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  widgetbook: ^3.2.0
  build_runner:
  widgetbook_generator:
  intl_utils:
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/mocks/
    - assets/anim/
flutter_intl:
  enabled: true