// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj3_7xIctivJJu91WesRdvWwXHYB6av_k',
    appId: '1:24272398369:web:1ef41d06b165f6ba1cdb60',
    messagingSenderId: '24272398369',
    projectId: 'flutter-template-369aa',
    authDomain: 'flutter-template-369aa.firebaseapp.com',
    storageBucket: 'flutter-template-369aa.appspot.com',
    measurementId: 'G-YLLB1GZ6D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkKn--UAkI0c-G8dJYs5ewTfBn-_nAdzw',
    appId: '1:24272398369:android:47564881ac1899c41cdb60',
    messagingSenderId: '24272398369',
    projectId: 'flutter-template-369aa',
    storageBucket: 'flutter-template-369aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr2dXywJtw0YA7cnmiiwkWgbCD-pgaXcE',
    appId: '1:24272398369:ios:97d40932fc6f581a1cdb60',
    messagingSenderId: '24272398369',
    projectId: 'flutter-template-369aa',
    storageBucket: 'flutter-template-369aa.appspot.com',
    iosClientId: '24272398369-747l8ad03hpremgmi08r4m4o6ndtcjjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTemplate3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr2dXywJtw0YA7cnmiiwkWgbCD-pgaXcE',
    appId: '1:24272398369:ios:97d40932fc6f581a1cdb60',
    messagingSenderId: '24272398369',
    projectId: 'flutter-template-369aa',
    storageBucket: 'flutter-template-369aa.appspot.com',
    iosClientId: '24272398369-747l8ad03hpremgmi08r4m4o6ndtcjjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTemplate3',
  );
}
